### ISSUE TITLE
Limit users who haven't paid

### ISSUE THREAD

**Issue by rtroyo** [cordageio/billing#11]
**When / Situation**: A client organization hasn't paid and want to use the system for free,
 **User Motivation**: Cordage needs to collect payment
 **So that:** it can keep the lights on.
**Expected Outcome:** Users at a non-paying client organization can't access some of their information and cannot edit or add anything new.

Ideas: In the JWT with the information, we can include 3 status: 1. Paid, 2. Payment-overdue, 3. Trial. Based on these statuses we can lock an organization.
  
**Tasks:** 
- [ ] Understand if traffic is common
- [ ] Understand if traffic is common
  
**Acceptance Criteria:**
- [ ] Must load in under .5 seconds with 100 registries

**Comment by Yamilquery** [comment]
Tasks

- [x] Add field status payment to organization (migration and schema)
- [x] Add dependency ecto_enum and configure to payment_status in organization

Acceptance criteria:

- [ ] Pass unit test "should succeed when valid payment status on creating an organization"
- [ ] Pass unit test "should ignore when invalid payment status on creating an organization"
- [ ] Pass integration test "..."
- [ ] Pass web test "..."
- [x] Should pass all the tests and run successfully in production server with CircleCI
